import { chromium } from 'playwright'
const OUT = process.argv[2]
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH })
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, permissions: ['camera'] })
const p = await ctx.newPage()
await p.goto('http://localhost:4176/login')
await p.waitForSelector('img[alt="RYLA Global Services"]')
await p.screenshot({ path: `${OUT}/brand-01-login.png` })
await p.fill('input[type=email]', 'driver@dp.test')
await p.fill('input[type=password]', 'x')
await p.click('button[type=submit]')
await p.waitForURL('**/driver')
await p.waitForSelector('text=Next pickup')
await p.screenshot({ path: `${OUT}/brand-02-driver.png` })
const m = await (await b.newContext({ viewport: { width: 1280, height: 900 } })).newPage()
await m.goto('http://localhost:4176/login')
await m.fill('input[type=email]', 'manager@dp.test')
await m.fill('input[type=password]', 'x')
await m.click('button[type=submit]')
await m.waitForURL('**/manager')
await m.waitForSelector('text=Vehicles scheduled')
await m.screenshot({ path: `${OUT}/brand-03-manager.png`, fullPage: true })
await b.close()
console.log('shots done')
