/**
 * Stages the OCR engine's runtime assets into public/ocr.
 *
 * tesseract.js fetches its worker script, wasm core and language data at
 * runtime, from a CDN by default. That is unacceptable here: a driver between
 * two stacks of containers has no signal, and an engine that needs one is an
 * engine that does not work when it is needed. Serving the assets from our own
 * origin lets the service worker precache them.
 *
 * Everything comes from installed packages — nothing is fetched at build time.
 * A build that reaches out to a CDN is a build that fails when the CDN does,
 * and it makes the bytes you ship depend on someone else's uptime. The
 * language data is ~4 MB, so the output directory is gitignored and this
 * script runs as part of `npm run build`.
 */
import { copyFile, mkdir, readFile, readdir, writeFile, access } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)
const OUT = new URL('../public/ocr/', import.meta.url).pathname
const LANG = 'eng'

await mkdir(OUT, { recursive: true })

async function exists(path) {
  try { await access(path); return true } catch { return false }
}

// 1. The worker script and the wasm core, both from the installed packages.
const workerSrc = require.resolve('tesseract.js/dist/worker.min.js')
await copyFile(workerSrc, join(OUT, 'worker.min.js'))

const coreDir = dirname(require.resolve('tesseract.js-core/package.json'))
// Every LSTM core variant, enumerated rather than listed.
//
// The engine chooses a build at runtime from the CPU features it finds —
// plain, simd, or relaxedsimd — and hardcoding the list means the day a new
// variant is preferred, OCR fails to load with an importScripts error and no
// obvious cause. The legacy (non-LSTM) cores are excluded: the worker is
// created with OEM 1, so they are ~9 MB that would be staged and never read.
const coreFiles = (await readdir(coreDir)).filter(
  (f) => /^tesseract-core(-[a-z]+)*-lstm\.(js|wasm|wasm\.js)$/.test(f),
)
if (coreFiles.length === 0) {
  throw new Error(`No LSTM cores found in ${coreDir}`)
}
for (const file of coreFiles) {
  await copyFile(join(coreDir, file), join(OUT, file))
}
console.log(`ocr: ${coreFiles.length} core files staged`)

// 2. The language data, from the installed @tesseract.js-data package.
//
// The "best_int" variant is the integer-quantised best model: noticeably more
// accurate than the fast model on low-contrast text, which is exactly the
// condition a stamped chassis plate presents, at a size that is still
// acceptable to precache.
const dataRoot = dirname(require.resolve('@tesseract.js-data/eng/package.json'))
const preferred = ['4.0.0_best_int', '4.0.0']
let staged = false
for (const variant of preferred) {
  const from = join(dataRoot, variant, `${LANG}.traineddata.gz`)
  if (await exists(from)) {
    await copyFile(from, join(OUT, `${LANG}.traineddata.gz`))
    console.log(`ocr: language data from ${variant}`)
    staged = true
    break
  }
}
if (!staged) {
  const found = await readdir(dataRoot)
  throw new Error(
    `No traineddata found in @tesseract.js-data/eng (saw: ${found.join(', ')})`,
  )
}

const manifest = {
  language: LANG,
  stagedAt: new Date().toISOString(),
  note: 'Generated by scripts/prepare-ocr.mjs. Do not edit by hand.',
}
await writeFile(join(OUT, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`)

const sizes = await Promise.all(
  ['worker.min.js', `${LANG}.traineddata.gz`].map(async (f) => {
    const buf = await readFile(join(OUT, f))
    return `${f} ${(buf.length / 1024).toFixed(0)} KB`
  }),
)
console.log('ocr: staged —', sizes.join(', '))
